/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	CompCtrlDefine.h
  * @author	 
  * @version 	
  * @date	
  * @brief	Store composite control define
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef COMP_CTRL_DEFINE_H
    #define COMP_CTRL_DEFINE_H
#endif	

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
