/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         Function.h
  * @author	 
  * @version 	
  * @date	
  * @brief	         Store quote of the function 
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef FUNCTION_H
    #define FUNCTION_H
#endif	

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
extern void IcResourceInit(void);
/*************************************.Generated by EasyCodeCube.************************************/
