/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	SysFunVarDefine.h
  * @author	 
  * @version 	
  * @date	
  * @brief	Store var control and function control extern
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef SYS_FUN_VAR_DEFINE
    #define SYS_FUN_VAR_DEFINE
#include "CustomType.h"
#include "UserExport.h"
#include "FunctionType.h"
#include "CompCtrlDefine.h"
#endif

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
