/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	CallBackFunction.c
  * @author	 
  * @version 	
  * @date	
  * @brief	Write the logic you want to implement in the function body
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
void Customer_BTM_Dispose()
{
/*<UserCodeStart>*//*<SinOne-Tag><387>*/
/*<UserCodeEnd>*//*<SinOne-Tag><387>*/
}
void Customer_IntoLowPowerMode_Init()
{
/*<UserCodeStart>*//*<SinOne-Tag><388>*/
/*<UserCodeEnd>*//*<SinOne-Tag><388>*/
}
void Customer_QuitLowPowerMode_Init()
{
/*<UserCodeStart>*//*<SinOne-Tag><389>*/
/*<UserCodeEnd>*//*<SinOne-Tag><389>*/
}
/*************************************.Generated by EasyCodeCube.************************************/
