/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	CompCtrlDefine.C
  * @author	 
  * @version 	
  * @date	
  * @brief	Store composite control define
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
void IcResourceInit(void)
{
    
    /*<UserCodeStart>*//*<SinOne-Tag><37>*/
        SC_Init(); /***MCU init***/
        
    /*<UserCodeEnd>*//*<SinOne-Tag><37>*/
    
}

/*************************************.Generated by EasyCodeCube.************************************/
