/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         main.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its H file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
/*******************Includes************************************************************************/

#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
#include "Buzzer.h"
#include "Delay.h"
#include "TKDriver.h"
#include "sc32f10xx_TK_ParameterAnalysis.h"
#include "adc_iap.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/

/**
 * @brief This function implements main function.
 * @note
 * @param
 */
int main(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<UserCodeStart>*//*<SinOne-Tag><36>*/
    IcResourceInit();
    TIM_Cmd(TIM2, DISABLE);
    Buzzer_SetVolume(50);
    TK_Init();                    //重要步骤1：TK的初始化函数
    /*读取掉电保存设置*/
    /*<UserCodeEnd>*//*<SinOne-Tag><36>*/
    
    /*<UserCodeStart>*//*<SinOne-Tag><4>*/
    /*****MainLoop*****/
    while(1)
    {
        /*<UserCodeStart>*//*<SinOne-Tag><14>*/
        /***User program***/
        
        switch(Task_state)
        {
            case 0:                                 // init
            GPIO_ResetBits(GPIOC, GPIO_Pin_4);  // LED1
            GPIO_ResetBits(GPIOC, GPIO_Pin_10); // LED3
            GPIO_ResetBits(GPIOC, GPIO_Pin_11); // LED4
            GPIO_ResetBits(GPIOA, GPIO_Pin_7);  // LED5
            GPIO_ResetBits(GPIOA, GPIO_Pin_8);  // LED6
            Task_state = 3;
            break;
            case 1:                             // TK task
            break;
            case 2: // Buzz SET
            break;
            case 3: // ADC SET
            
            
            
            
            
            
            
            
            
            break;
            case 4: // ADC get
            ADC_value = ADC_GetConversionValue(ADC);
            break;
        }
        
        /*<UserCodeEnd>*//*<SinOne-Tag><14>*/
        /*<UserCodeStart>*//*<SinOne-Tag><77>*/
        /*<UserCodeEnd>*//*<SinOne-Tag><77>*/
        /*<UserCodeStart>*//*<SinOne-Tag><412>*/
        IAP_Program();
        /*<UserCodeEnd>*//*<SinOne-Tag><412>*/
        /*<Begin-Inserted by EasyCodeCube for Condition>*/
    }
    /*<UserCodeEnd>*//*<SinOne-Tag><4>*/
    /*<Generated by EasyCodeCube end>*/
}

void Delay_us(uint16_t xus)
{
    TIM_Cmd(TIM1,ENABLE); 
    while(TIM1->TIM_CNT < xus);
    TIM1->TIM_CNT = 0;
    TIM_Cmd(TIM1,DISABLE); 
}

void Delay_ms(uint16_t xms)
{
    int i;
    for (i = 0; i < xms; i++)
    {
        Delay_us(1000);
    }
}

