/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         main.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its H file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
/*******************Includes************************************************************************/

#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
#include "Buzzer.h"
#include "Delay.h"
#include "TKDriver.h"
#include "sc32f10xx_TK_ParameterAnalysis.h"
#include "adc_iap.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
uint8_t Task_state;
uint16_t ADC_value1;
uint16_t ADC_value2;
ADC_ChannelTypedef Channel;
float Voltage;
AlarmSettings LED;
uint8_t exKeyValue = 0;
uint8_t gTkIsValid = 0;
uint8_t Task_state = 0;
uint32_t TK_exKeyValueFlag;
void DataProcessing(uint32_t value)
{
    switch (TK_exKeyValueFlag)
    {
    case 0x00040000:
        exKeyValue = 18;// 模式/确认
        break;
    case 0x00020000:
        exKeyValue = 17;// 返回
        break;
    default:
        exKeyValue = 0xff;
        break;
    }
}
uint8_t first_Press;
uint8_t cnt;
void UpdateDisplay(uint8_t KeyValue)
{
    if (exKeyValue != 0XFF) // 松手前只出一次键
    {
        gTkIsValid = 1;
        KeyValue = exKeyValue;
        if (first_Press == 0)
        {
            if (KeyValue == 17)
            {
                cnt++;
            }
            else if (KeyValue == 18)
            {
                cnt = 0;
                // 先关灯
                GPIO_SetBits(GPIOC, GPIO_Pin_4 | GPIO_Pin_5 | GPIO_Pin_10 | GPIO_Pin_11); // 先关闭所有 LED
                GPIO_SetBits(GPIOA, GPIO_Pin_7 | GPIO_Pin_8);                             // 先关闭所有 LED
            }

            first_Press = 1;
        }
    }
    else
    {
        gTkIsValid = 0;
        first_Press = 0;
    }
}
void test_TK_LED(uint8_t cnt_LED)
{
    // 根据 cnt 的值点亮相应数量的 LED
    if (cnt_LED >= 1)
        GPIO_ResetBits(GPIOC, GPIO_Pin_4); // LED1
    if (cnt_LED >= 2)
        GPIO_ResetBits(GPIOC, GPIO_Pin_5); // LED2
    if (cnt_LED >= 3)
        GPIO_ResetBits(GPIOC, GPIO_Pin_10); // LED3
    if (cnt_LED >= 4)
        GPIO_ResetBits(GPIOC, GPIO_Pin_11); // LED4
    if (cnt_LED >= 5)
        GPIO_ResetBits(GPIOA, GPIO_Pin_7); // LED5
    if (cnt_LED >= 6)
        GPIO_ResetBits(GPIOA, GPIO_Pin_8); // LED6
}
/**
 * @brief This function implements main function.
 * @note
 * @param
 */
uint8_t b;
uint32_t tim_cnt1;
uint32_t tim_cnt2;
int main(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<UserCodeStart>*//*<SinOne-Tag><36>*/
    IcResourceInit();
    TIM_Cmd(TIM2, DISABLE);
    //Buzzer_SetVolume(50);
    TK_Init();                    //重要步骤1：TK的初始化函数
    /*读取掉电保存设置*/
    loadAlarmSettings();
    Delay_ms(500);//延迟启动
    /*<UserCodeEnd>*//*<SinOne-Tag><36>*/

    /*<UserCodeStart>*/ /*<SinOne-Tag><4>*/
    /*****MainLoop*****/
    while (1)
    {
        /*<UserCodeStart>*/ /*<SinOne-Tag><14>*/
        /***User program***/
        // b = IAP_Program();
        switch (Task_state)
        {
        case 0: // init
            Task_state = 1;
            break;
        case 1:           
            /*检查掉电*/
            checkPowerLoss(cnt);
        
            /*TK*/
            WDT->WDT_CON |= WDT_CON_CLRWDT; // 清watchdog

            // 重要步骤2：触摸键扫描一轮标志，是否调用TouchKeyScan()一定要根据此标志位置起�?
            if (TK_TouchKeyStatus & 0x80)
            { // 重要步骤3：清除标志位，需要外部清零
                TK_TouchKeyStatus &= 0x7f;
                // 重要步骤4：分析按键数据，并返回结果出来
                TK_exKeyValueFlag = TK_TouchKeyScan();
                DataProcessing(TK_exKeyValueFlag); // 按键数据处理函数

                UpdateDisplay(exKeyValue);
                TK_Restart(); // 启动下一轮转换
            }
            test_TK_LED(cnt); // 测试点灯
            
            
            /*程序运行判断*/
            tim_cnt1++;
            if (tim_cnt1 % 20 == 0)
            {
                tim_cnt2++;
                if (tim_cnt2 % 30 == 0)
                {
                    GPIO_TogglePins(GPIOA, GPIO_Pin_8);
                }
            }

            break;
        case 2: // Buzz SET
            break;
        case 3: // ADC SET       
            break;
            case 4: // ADC get
            
            break;
            }

        /*<UserCodeEnd>*//*<SinOne-Tag><14>*/
        /*<UserCodeStart>*//*<SinOne-Tag><77>*/
        /*<UserCodeEnd>*//*<SinOne-Tag><77>*/
        /*<UserCodeStart>*//*<SinOne-Tag><412>*/
        //IAP_Program();
        /*<UserCodeEnd>*//*<SinOne-Tag><412>*/
        /*<Begin-Inserted by EasyCodeCube for Condition>*/
    }
    /*<UserCodeEnd>*//*<SinOne-Tag><4>*/
    /*<Generated by EasyCodeCube end>*/
}

void Delay_us(uint16_t xus)
{
    TIM_Cmd(TIM1,ENABLE); 
    while(TIM1->TIM_CNT < xus);
    TIM1->TIM_CNT = 0;
    TIM_Cmd(TIM1,DISABLE); 
}

void Delay_ms(uint16_t xms)
{
    int i;
    for (i = 0; i < xms; i++)
    {
        Delay_us(1000);
    }
}

