/**
 *****************************************************************************************************
  * @copyright	(c)  
  * @file	         SC_it.h
  * @author	 
  * @version 	     
  * @date	         2024.03.11
  * @brief	         Interrupt service program header file
  * @details         
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef _SC_IT_H_
#define	_SC_IT_H_

#include "sc32_conf.h"

void INT0_IRQHandler(void);
void INT1_7_IRQHandler(void);
void INT8_11_IRQHandler(void);
void INT12_15_IRQHandler(void);
void RCC_IRQHandler(void);
#if !defined (TK_USE_BTM)
void BTM_IRQHandler(void);
#endif
#if defined (SC32f10xx)
	#if !defined (TK_USE_UART0_2)
	void UART0_2_IRQHandler(void);
	#endif
	
	#if !defined (TK_USE_UART1_3)
	void UART1_3_IRQHandler(void);
	#endif
#elif defined (SC32f12xx)
	#if !defined (TK_USE_UART0_2_4)
		void UART0_2_4_IRQHandler(void);
	#endif
	
	#if !defined (TK_USE_UART1_3_5)
		void UART1_3_5_IRQHandler(void);
	#endif
#endif
void SPI0_IRQHandler(void);
#if defined (SC32f10xx)
void SPI1_IRQHandler(void);
#elif defined (SC32f12xx)
void SPI1_2_IRQHandler(void);
#endif
void DMA0_IRQHandler(void);
void DMA1_IRQHandler(void);
#if defined (SC32f10xx)
void DMA2_IRQHandler(void);
void DMA3_IRQHandler(void);
#endif
void TIMER0_IRQHandler(void);
void TIMER1_IRQHandler(void);
void TIMER2_IRQHandler(void);
void TIMER3_IRQHandler(void);
void TIMER4_5_IRQHandler(void);
void TIMER6_7_IRQHandler(void);
void PWM0_IRQHandler(void);
void LEDPWM_IRQHandler(void);
void TWI0_IRQHandler(void);
void TWI1_IRQHandler(void);
void ADC_IRQHandler(void);
void CMP_IRQHandler(void);
void SysTick_IRQHandler(void);
#endif


/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/
