/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"



/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	SC_GPIO_Init();
	SC_OPTION_Init();
	SC_RCC_Init();
	SC_SYSTICK_Init();
	SC_UART1_Init();
	SC_UART2_Init();
	SC_TWI0_Init();
	SC_TIM1_Init();
	SC_TIM2_Init();
	SC_TIM3_Init();
	SC_PWM0_Init();
	SC_ADC_Init();
	SC_DMA0_Init();
	SC_DMA1_Init();
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_HXTCmd(DISABLE);
	RCC_LXTCmd(DISABLE);
	RCC_LIRCCmd(ENABLE);
	RCC_HIRCCmd(ENABLE);
	/*INTEN*/RCC_ITConfig(ENABLE);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HIRC);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_APB0Config(RCC_HCLK_Div1);
	RCC_APB0Cmd(ENABLE);
	RCC_APB1Config(RCC_HCLK_Div1);
	RCC_APB1Cmd(ENABLE);
	RCC_APB2Config(RCC_HCLK_Div1);
	RCC_APB2Cmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_SystickCLKConfig(RCC_SysTickSource_HCLK_DIV8);
	RCC_SystickSetCounter(16000);
	NVIC_SetPriority(SysTick_IRQn,0);
	RCC_SystickCmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	SC32F10xSx_NIO_Init();
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
    /*GPIOInit_PB07 Struct*/GPIO_InitTypeDef GPIOInit_PB07_Struct;
    GPIOInit_PB07_Struct.GPIO_Pin = GPIO_Pin_7;
    GPIOInit_PB07_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PB07_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOB,&GPIOInit_PB07_Struct);/*TK17端口初始化*/
    /*GPIOInit_PB08 Struct*/GPIO_InitTypeDef GPIOInit_PB08_Struct;
    GPIOInit_PB08_Struct.GPIO_Pin = GPIO_Pin_8;
    GPIOInit_PB08_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PB08_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOB,&GPIOInit_PB08_Struct);/*TK18端口初始化*/
	/*GPIOInit_PC04 Struct*/GPIO_InitTypeDef GPIOInit_PC04_Struct;
	GPIOInit_PC04_Struct.GPIO_Pin = GPIO_Pin_4;
	GPIOInit_PC04_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC04_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC04_Struct);/*PC.04端口初始化*/
	/*GPIOInit_PC05 Struct*/GPIO_InitTypeDef GPIOInit_PC05_Struct;
	GPIOInit_PC05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PC05_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC05_Struct);/*PC.05端口初始化*/
	/*GPIOInit_PC10 Struct*/GPIO_InitTypeDef GPIOInit_PC10_Struct;
	GPIOInit_PC10_Struct.GPIO_Pin = GPIO_Pin_10;
	GPIOInit_PC10_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC10_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC10_Struct);/*PC.10端口初始化*/
	/*GPIOInit_PC11 Struct*/GPIO_InitTypeDef GPIOInit_PC11_Struct;
	GPIOInit_PC11_Struct.GPIO_Pin = GPIO_Pin_11;
	GPIOInit_PC11_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC11_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC11_Struct);/*PC.11端口初始化*/
	/*GPIOInit_PA07 Struct*/GPIO_InitTypeDef GPIOInit_PA07_Struct;
	GPIOInit_PA07_Struct.GPIO_Pin = GPIO_Pin_7;
	GPIOInit_PA07_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA07_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA07_Struct);/*PA.07端口初始化*/
	/*GPIOInit_PA08 Struct*/GPIO_InitTypeDef GPIOInit_PA08_Struct;
	GPIOInit_PA08_Struct.GPIO_Pin = GPIO_Pin_8;
	GPIOInit_PA08_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA08_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA08_Struct);/*PA.08端口初始化*/
	/*GPIOInit_PA09 Struct*/GPIO_InitTypeDef GPIOInit_PA09_Struct;
	GPIOInit_PA09_Struct.GPIO_Pin = GPIO_Pin_9;
	GPIOInit_PA09_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA09_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA09_Struct);/*PA.09端口初始化*/
	/*GPIOInit_PA11 Struct*/GPIO_InitTypeDef GPIOInit_PA11_Struct;
	GPIOInit_PA11_Struct.GPIO_Pin = GPIO_Pin_11;
	GPIOInit_PA11_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA11_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA11_Struct);/*PA.11端口初始化*/
	/*GPIOInit_PA12 Struct*/GPIO_InitTypeDef GPIOInit_PA12_Struct;
	GPIOInit_PA12_Struct.GPIO_Pin = GPIO_Pin_12;
	GPIOInit_PA12_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA12_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA12_Struct);/*PA.12端口初始化*/
	/*GPIOInit_PB01 Struct*/GPIO_InitTypeDef GPIOInit_PB01_Struct;
	GPIOInit_PB01_Struct.GPIO_Pin = GPIO_Pin_1;
	GPIOInit_PB01_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB01_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB01_Struct);/*PB.01端口初始化*/
	/*GPIOInit_PB02 Struct*/GPIO_InitTypeDef GPIOInit_PB02_Struct;
	GPIOInit_PB02_Struct.GPIO_Pin = GPIO_Pin_2;
	GPIOInit_PB02_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB02_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB02_Struct);/*PB.02端口初始化*/
	/*GPIOInit_PB03 Struct*/GPIO_InitTypeDef GPIOInit_PB03_Struct;
	GPIOInit_PB03_Struct.GPIO_Pin = GPIO_Pin_3;
	GPIOInit_PB03_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB03_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB03_Struct);/*PB.03端口初始化*/
	/*GPIOInit_PB04 Struct*/GPIO_InitTypeDef GPIOInit_PB04_Struct;
	GPIOInit_PB04_Struct.GPIO_Pin = GPIO_Pin_4;
	GPIOInit_PB04_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB04_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB04_Struct);/*PB.04端口初始化*/
	/*GPIOInit_PB05 Struct*/GPIO_InitTypeDef GPIOInit_PB05_Struct;
	GPIOInit_PB05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PB05_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB05_Struct);/*PB.05端口初始化*/
	/*GPIOInit_PB06 Struct*/GPIO_InitTypeDef GPIOInit_PB06_Struct;
	GPIOInit_PB06_Struct.GPIO_Pin = GPIO_Pin_6;
	GPIOInit_PB06_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB06_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB06_Struct);/*PB.06端口初始化*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PA13 Struct*/GPIO_InitTypeDef GPIOInit_PA13_Struct;
	GPIOInit_PA13_Struct.GPIO_Pin = GPIO_Pin_13;
	GPIOInit_PA13_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA13_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA13_Struct);/*RX1端口初始化*/
	/*GPIOInit_PA14 Struct*/GPIO_InitTypeDef GPIOInit_PA14_Struct;
	GPIOInit_PA14_Struct.GPIO_Pin = GPIO_Pin_14;
	GPIOInit_PA14_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA14_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA14_Struct);/*TX1端口初始化*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_UART1, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 32000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode =  UART_Mode_10B;
	UART_Init(UART1, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART1,UART_IT_EN,ENABLE);
	/*INT_TX*/UART_ITConfig(UART1,UART_IT_TX,DISABLE);
	/*INT_RX*/UART_ITConfig(UART1,UART_IT_RX,ENABLE);
	/*DMA_TX*/UART_DMACmd(UART1,UART_DMAReq_TX,DISABLE);
	/*DMA_RX*/UART_DMACmd(UART1,UART_DMAReq_RX,DISABLE);
	/*Init Struct*/NVIC_SetPriority(UART1_3_IRQn,3);/*UART1_3*/
	NVIC_EnableIRQ(UART1_3_IRQn);
	/*Init Struct*/UART_PinRemapConfig(UART1,UART_PinRemap_Default);
	UART_TXCmd(UART1,ENABLE);
	UART_RXCmd(UART1,ENABLE);
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PA15 Struct*/GPIO_InitTypeDef GPIOInit_PA15_Struct;
	GPIOInit_PA15_Struct.GPIO_Pin = GPIO_Pin_15;
	GPIOInit_PA15_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA15_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA15_Struct);/*TX2端口初始化*/
	/*GPIOInit_PB00 Struct*/GPIO_InitTypeDef GPIOInit_PB00_Struct;
	GPIOInit_PB00_Struct.GPIO_Pin = GPIO_Pin_0;
	GPIOInit_PB00_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PB00_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB00_Struct);/*RX2端口初始化*/
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_UART2, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 32000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode =  UART_Mode_10B;
	UART_Init(UART2, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART2,UART_IT_EN,ENABLE);
	/*INT_TX*/UART_ITConfig(UART2,UART_IT_TX,DISABLE);
	/*INT_RX*/UART_ITConfig(UART2,UART_IT_RX,ENABLE);
	/*Init Struct*/NVIC_SetPriority(UART0_2_IRQn,3);/*UART0_2*/
	NVIC_EnableIRQ(UART0_2_IRQn);
	/*Init Struct*/UART_PinRemapConfig(UART2,UART_PinRemap_Default);
	UART_TXCmd(UART2,ENABLE);
	UART_RXCmd(UART2,ENABLE);
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TIM1,ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_32;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInitStruct.TIM_Preload = 33536;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM1, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Disable;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Disable;
	TIM_ICInit(TIM1, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM1, DISABLE);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM1, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM1, TIM_PWMChannel_PWMA,50);
	/*INTEN*/TIM_ITConfig(TIM1,TIM_IT_INTEN, DISABLE);
	/*CAPR*/TIM_DMACmd(TIM1,TIM_DMAReq_CAPR,ENABLE);
	/*CAPF*/TIM_DMACmd(TIM1,TIM_DMAReq_CAPF,ENABLE);
	TIM_DMACmd(TIM1,TIM_DMAReq_TI,ENABLE);
	TIM_Cmd(TIM1,ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TIM2,ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_1;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInitStruct.TIM_Preload = 65536-(32000000/1000);
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM2, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Disable;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Disable;
	TIM_ICInit(TIM2, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM2, DISABLE);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM2, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM2, TIM_PWMChannel_PWMA,50);
	/*INTEN*/TIM_ITConfig(TIM2,TIM_IT_INTEN, DISABLE);
	/*CAPR*/TIM_DMACmd(TIM2,TIM_DMAReq_CAPR,ENABLE);
	/*CAPF*/TIM_DMACmd(TIM2,TIM_DMAReq_CAPF,DISABLE);
	/*TI*/TIM_DMACmd(TIM2,TIM_DMAReq_TI,ENABLE);
	TIM_Cmd(TIM2,ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TIM3,ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_1;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInitStruct.TIM_Preload = 33536;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM3, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Disable;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Disable;
	TIM_ICInit(TIM3, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM3, DISABLE);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM3, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM3, TIM_PWMChannel_PWMA,50);
	/*INTEN*/TIM_ITConfig(TIM3,TIM_IT_INTEN, DISABLE);
	/*Init Struct*/NVIC_SetPriority(TIMER3_IRQn,3);/*TIMER3*/
	NVIC_EnableIRQ(TIMER3_IRQn);
	TIM_Cmd(TIM3,ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_PWM0,ENABLE);
	/*PWM00*/PWM_SetDuty(PWM0,PWM_Channel_0,0);
	/*PWM01*/PWM_SetDuty(PWM0,PWM_Channel_1,99);
	/*PWM02*/PWM_SetDuty(PWM0,PWM_Channel_2,99);
	/*PWM03*/PWM_SetDuty(PWM0,PWM_Channel_3,99);
	/*PWM04*/PWM_SetDuty(PWM0,PWM_Channel_4,0);
	/*PWM05*/PWM_SetDuty(PWM0,PWM_Channel_5,0);
	/*PWM06*/PWM_SetDuty(PWM0,PWM_Channel_6,0);
	/*PWM07*/PWM_SetDuty(PWM0,PWM_Channel_7,0);
	/*Init Struct*/PWM_InitTypeDef PWM_InitStruct;
	PWM_InitStruct.PWM_WorkMode = PWM_WorkMode_Independent;
	PWM_InitStruct.PWM_Prescaler = PWM_PRESCALER_DIV8;
	PWM_InitStruct.PWM_Cycle = 99;
	PWM_InitStruct.PWM_OutputChannel = PWMChannel_Less|PWM_Channel_1|PWM_Channel_2|PWM_Channel_3;
	PWM_InitStruct.PWM_LowPolarityChannl = PWMChannel_Less;
	PWM_InitStruct.PWM_AlignedMode = PWM_AlignmentMode_Edge;
	PWM_Init(PWM0,&PWM_InitStruct);
	/*Init Struct*/PWM_FDInitTypeDef PWM_FDInitStruct;
	PWM_FDInitStruct.PWM_FDMode = PWM_FDMode_Immediate;
	PWM_FDInitStruct.PWM_FDVoltage = PWM_FDVoltage_Low;
	PWM_FDInitStruct.PWM_FDFilteringTime = PWM_FilteringTime_0us;
	PWM_FDInit(PWM0, &PWM_FDInitStruct);
	PWM_FDCmd(PWM0,DISABLE);
	/*INTEN*/PWM_ITConfig(PWM0,PWM_IT_INTEN,DISABLE);
	PWM_Cmd(PWM0,ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*Init Struct*/ADC_InitTypeDef ADC_Base_InitStruct;
	ADC_Base_InitStruct.ADC_ConvMode = ADC_ConvMode_Single;
	ADC_Base_InitStruct.ADC_Prescaler = ADC_Prescaler_3CLOCK;
	ADC_Base_InitStruct.ADC_EAIN = ADC_EAIN_Less|ADC_EAIN_13|ADC_EAIN_14;
	ADC_Base_InitStruct.ADC_VREF = ADC_VREF_2_4V;
	ADC_Init(ADC, &ADC_Base_InitStruct);
	ADC_SetChannel(ADC,ADC_Channel_VDD_D4);
	/*ADCIF*/ADC_ITConfig(ADC,ADC_IT_ADCIF, DISABLE);
	ADC_DMACmd(ADC,ENABLE);
	/*Init Struct*/NVIC_SetPriority(ADC_IRQn,3);/*ADC*/
	NVIC_EnableIRQ(ADC_IRQn);
	ADC_Cmd(ADC,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief VREF init
  * @note 
  * @param
  */
void SC_VREF_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DAC init
  * @note 
  * @param
  */
void SC_DAC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TemperSensor init
  * @note 
  * @param
  */
void SC_TemperSensor_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief PCAP init
  * @note 
  * @param
  */
void SC_PCAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief EPWM init
  * @note 
  * @param
  */
void SC_EPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}





/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief OP0 init
  * @note 
  * @param
  */
void SC_OP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}
/**
  * @brief OP1 init
  * @note 
  * @param
  */
void SC_OP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief OP2 init
  * @note 
  * @param
  */
void SC_OP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief QEP0 init
  * @note 
  * @param
  */
void SC_QEP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief QEP1 init
  * @note 
  * @param
  */
void SC_QEP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}




/**
  * @brief CAN init
  * @note 
  * @param
  */
void SC_CAN_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PA05 Struct*/GPIO_InitTypeDef GPIOInit_PA05_Struct;
	GPIOInit_PA05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PA05_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA05_Struct);/*SDA0B端口初始化*/
	/*GPIOInit_PA06 Struct*/GPIO_InitTypeDef GPIOInit_PA06_Struct;
	GPIOInit_PA06_Struct.GPIO_Pin = GPIO_Pin_6;
	GPIOInit_PA06_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA06_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA06_Struct);/*SCL0B端口初始化*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TWI0, ENABLE);
	/*Init Struct*/TWI_InitTypeDef TWI_InitStruct;
	TWI_InitStruct.TWI_Ack = TWI_Ack_Enable;
	TWI_InitStruct.TWI_Prescaler = TWI_PRESCALER_128;
	TWI_InitStruct.TWI_Stretch = TWI_Stretch_Disable;
	TWI_InitStruct.TWI_SlaveAdress = 0x50;
	TWI_InitStruct.TWI_GeneralCall = TWI_GeneralCall_Disable;
	TWI_Init(TWI0, &TWI_InitStruct);
	TWI_PinRemapConfig(TWI0,TWI_PinRemap_B);
	/*INT*/TWI_ITConfig(TWI0,TWI_IT_INT,ENABLE);
	/*DMA_TX*/TWI_DMACmd(TWI0,TWI_DMAReq_TX,DISABLE);
	/*DMA_RX*/TWI_DMACmd(TWI0,TWI_DMAReq_RX,DISABLE);
	/*Init Struct*/NVIC_SetPriority(TWI0_IRQn,3);/*TWI0*/
	NVIC_EnableIRQ(TWI0_IRQn);
	TWI_Cmd(TWI0,ENABLE);
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA,ENABLE);
	/*Init Struct*/DMA_InitTypeDef DMA_InitStruct;
	DMA_InitStruct.DMA_Priority = DMA_Priority_HIGH;
	DMA_InitStruct.DMA_TargetMode = DMA_TargetMode_FIXED;
	DMA_InitStruct.DMA_SourceMode = DMA_SourceMode_INC_CIRC;
	DMA_InitStruct.DMA_SrcAddress = (uint32_t)UART_Communication_DMA_Data;
	DMA_InitStruct.DMA_DstAddress = (uint32_t)& UART1->UART_DATA;
	DMA_InitStruct.DMA_DataSize = DMA_DataSize_Byte;
	DMA_InitStruct.DMA_Burst = DMA_Burst_Disable;
	DMA_InitStruct.DMA_Request = DMA_Request_UART1_TX;
	DMA_InitStruct.DMA_BufferSize = 0xC8;
	DMA_InitStruct.DMA_CircularMode = DMA_CircularMode_Disable;
	DMA_Init(DMA0, &DMA_InitStruct);
	/*INTEN*/DMA_ITConfig(DMA0,DMA_IT_INTEN, ENABLE);
	/*TEIE*/DMA_ITConfig(DMA0,DMA_IT_TEIE, DISABLE);
	/*HTIE*/DMA_ITConfig(DMA0,DMA_IT_HTIE, DISABLE);
	/*TCIE*/DMA_ITConfig(DMA0,DMA_IT_TCIE, ENABLE);
	DMA_DMACmd(DMA0,DMA_DMAReq_CHRQ,DISABLE);
	/*Init Struct*/NVIC_SetPriority(DMA0_IRQn,3);/*DMA0*/
	NVIC_EnableIRQ(DMA0_IRQn);
	DMA_Cmd(DMA0,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA,ENABLE);
	/*Init Struct*/DMA_InitTypeDef DMA_InitStruct;
	DMA_InitStruct.DMA_Priority = DMA_Priority_VERY_HIGH;
	DMA_InitStruct.DMA_TargetMode = DMA_TargetMode_INC_CIRC;
	DMA_InitStruct.DMA_SourceMode = DMA_SourceMode_FIXED;
	DMA_InitStruct.DMA_SrcAddress = (uint32_t)& UART1->UART_DATA;
	DMA_InitStruct.DMA_DstAddress = (uint32_t)UART_Communication_DMA_Data;
	DMA_InitStruct.DMA_DataSize = DMA_DataSize_Byte;
	DMA_InitStruct.DMA_Burst = DMA_Burst_Disable;
	DMA_InitStruct.DMA_Request = DMA_Request_UART1_RX;
	DMA_InitStruct.DMA_BufferSize = 0xC8;
	DMA_InitStruct.DMA_CircularMode = DMA_CircularMode_Enable;
	DMA_Init(DMA1, &DMA_InitStruct);
	/*INTEN*/DMA_ITConfig(DMA1,DMA_IT_INTEN, ENABLE);
	/*TEIE*/DMA_ITConfig(DMA1,DMA_IT_TEIE, DISABLE);
	/*HTIE*/DMA_ITConfig(DMA1,DMA_IT_HTIE, DISABLE);
	/*TCIE*/DMA_ITConfig(DMA1,DMA_IT_TCIE, ENABLE);
	DMA_DMACmd(DMA1,DMA_DMAReq_CHRQ,DISABLE);
	/*Init Struct*/NVIC_SetPriority(DMA1_IRQn,3);/*DMA1*/
	NVIC_EnableIRQ(DMA1_IRQn);
	DMA_Cmd(DMA1,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief LCD init
  * @note 
  * @param
  */

void SC_LCD_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC LED Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief SC MR Init
  * @note 
  * @param
  */
void SC_MR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP Init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP0 Init
  * @note 
  * @param
  */
void SC_ACMP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP1 Init
  * @note 
  * @param
  */
void SC_ACMP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP2 Init
  * @note 
  * @param
  */
void SC_ACMP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP3 Init
  * @note 
  * @param
  */
void SC_ACMP3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
  /*<Generated by EasyCodeCube end>*/	
}































