/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.h
  * @author	 
  * @version 	     
  * @date	         2024.03.11
  * @brief	         Contains the MCU initialization function and its H file
  * @details         
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#ifndef _SC_INIT_H_
#define _SC_INIT_H_

#include "sc32_conf.h"

void SC_Init(void);
void SC_NVIC_Init(void);
void SC_SYSTICK_Init(void);
void SC_RCC_Init(void);
void SC_OPTION_Init(void);
void SC_GPIO_Init(void);
void SC_UART0_Init(void);
void SC_UART1_Init(void);
void SC_UART2_Init(void);
void SC_UART3_Init(void);
#if defined (SC32f12xx)
void SC_UART4_Init(void);
void SC_UART5_Init(void);
#endif
void SC_TIM0_Init(void);
void SC_TIM1_Init(void);
void SC_TIM2_Init(void);
void SC_TIM3_Init(void);
void SC_TIM4_Init(void);
void SC_TIM5_Init(void);
void SC_TIM6_Init(void);
void SC_TIM7_Init(void);
void SC_PWM0_Init(void);
void SC_LEDPWM_Init(void);
void SC_INT_Init(void);
void SC_ADC_Init(void);
void SC_IAP_Init(void);
void SC_TWI1_Init(void);
void SC_TWI0_Init(void);
void SC_SPI0_Init(void);
void SC_SPI1_Init(void);
#if defined (SC32f12xx)
void SC_SPI2_Init(void);
#endif
void SC_BTM_Init(void);
void SC_CRC_Init(void);
void SC_DMA0_Init(void);
void SC_DMA1_Init(void);
#if defined (SC32f10xx)
void SC_DMA2_Init(void);
void SC_DMA3_Init(void);
#endif
void SC_WDT_Init(void);
void SC_PWR_Init(void);
void SC_LCD_Init(void);
void SC_LED_Init(void);
void SC_ACMP_Init(void);
#if defined (SC32f12xx)
void SC_OP_Init(void);
#endif
#endif

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/
